var dropdownOptions=[
    {region:`Other Countries`, country:`United Arab Emirates`, city:`Dubai`, campus:`AE007OF01 CG ONECENTRAL`, building:`ONECENTRAL`},
    {region:`Americas`, country:`Argentina`, city:`Buenos Aires`, campus:`AR004OF01 Buenos Aires Tucuman 1`, building:`TUCUMAN`},
    {region:`Europe`, country:`Austria`, city:`Wien`, campus:`AT002OF01 Wien Handelskai`, building:`HANDELSKAI`},
    {region:`APAC`, country:`Australia`, city:`Adelaide`, campus:`AU002OF01 Adelaide Grenfell`, building:`GRENFELL`},
    {region:`APAC`, country:`Australia`, city:`Melbourne`, campus:`AU003OF02 Melbourne Collinss`, building:`COLLINSS`},
    {region:`APAC`, country:`Australia`, city:`Wendouree`, campus:`AU007OF01 Wendouree Gillies Street`, building:`GILLIESSTREET`},
    {region:`APAC`, country:`Australia`, city:`Canberra`, campus:`AU014OF01 Canberra Bunda Street`, building:`BUNDASTREET`},
    {region:`APAC`, country:`Australia`, city:`Perth`, campus:`AU015OF01 Perth William Street`, building:`WILLIAMSTREET`},
    {region:`APAC`, country:`Australia`, city:`Brisbane`, campus:`AU018OF01 Brisbane Creek Street`, building:`CREEKSTREET`},
    {region:`APAC`, country:`Australia`, city:`Hobart`, campus:`AU019OF01 Hobart Franklinwharf`, building:`FRANKLINWHARF`},
    {region:`APAC`, country:`Australia`, city:`Sydney`, campus:`AU020OF01 Sydney GeorgeStreet`, building:`GEORGESTREET`},
    {region:`Europe`, country:`Belgium`, city:`Gent (Ghent)`, campus:`BE007OF01 Gent Ottergemsesteen (AL)`, building:`OTTERGEMSESTEEN`},
    {region:`Europe`, country:`Belgium`, city:`Diegem`, campus:`BE011OF01 Diegem Park 7`, building:`PARK7`},
    {region:`Americas`, country:`Brazil`, city:`Campinas`, campus:`BR013OF01 Campinas Square C`, building:`CAMPINAS`},
    {region:`Americas`, country:`Brazil`, city:`Blumenau`, campus:`BR024OF01 Blumenau Rua`, building:`BLUMENAU`},
    {region:`Americas`, country:`Brazil`, city:`São Paulo`, campus:`BR037OF01 Sao Paulo (RDI)`, building:`RDI`},
    {region:`Americas`, country:`Brazil`, city:`Barueri`, campus:`BR045OF01 Barueri Alphavillenwt`, building:`ALPHAVILLENWT`},
    {region:`Americas`, country:`Brazil`, city:`São Paulo`, campus:`BR050OF01 Sao Paulo AVPRESOF`, building:`SAOPAULOAVPRES`},
    {region:`Americas`, country:`Canada`, city:`Mississauga`, campus:`CA017OF01 Mississauga Techavenue`, building:`TECHAVENUE`},
    {region:`Americas`, country:`Canada`, city:`Mississauga`, campus:`CA019OF01 Mississauga Nashuadrive (AL)`, building:`NASHUADRIVE`},
    {region:`Americas`, country:`Canada`, city:`Toronto`, campus:`CA024OF01 Toronto 81Baystreet`, building:`81BAYSTREET`},
    {region:`Americas`, country:`Canada`, city:`Calgary`, campus:`CA025OF01 Calgary Telus Sky`, building:`CALGARY`},
    {region:`Americas`, country:`Canada`, city:`Montréal-Nord`, campus:`CA028OF01 Montreal Nord MCGILLCOLLEGE`, building:`MCGILLCOLLEGE`},
    {region:`Americas`, country:`Canada`, city:`Calgary`, campus:`CA030E01 CALGARY6AVE`, building:`CALGARY6AVE`},
    {region:`Europe`, country:`Switzerland`, city:`Genève`, campus:`CH012OF01 Geneve Casai`, building:`CASAI`},
    {region:`Europe`, country:`Switzerland`, city:`Lausanne`, campus:`CH014OF01 Lausanne Rumine13 (AL)`, building:`RUMINE13`},
    {region:`Europe`, country:`Switzerland`, city:`Basel`, campus:`CH016OF01 Basel Aeschenvorstad (AL)`, building:`AESCHENVORSTAD`},
    {region:`APAC`, country:`China`, city:`Hangzhou`, campus:`CN001OF01 Hangzhou Tiantang`, building:`TIANTANG`},
    {region:`APAC`, country:`China`, city:`Shanghai`, campus:`CN005OF01 Shanghai Lujiazui`, building:`LUJIAZUI`},
    {region:`APAC`, country:`China`, city:`Guangzhou`, campus:`CN007OF01 Guangzhou Nanhai`, building:`NANHAI`},
    {region:`APAC`, country:`China`, city:`Guangzhou`, campus:`CN016OF01 Guangzhou Guojidianzi`, building:`GUOJIDIANZI`},
    {region:`APAC`, country:`China`, city:`Shenyang`, campus:`CN017OF01 Shenyang Xindi`, building:`XINDI`},
    {region:`APAC`, country:`China`, city:`Xian`, campus:`CN021OF01 Xian Software New Town (AL)`, building:`SOFTWARENEWTOWN`},
    {region:`APAC`, country:`China`, city:`Shanghai`, campus:`CN022OF01 Shanghai Changning Road (AL)`, building:`CHANGNINGROAD`},
    {region:`APAC`, country:`China`, city:`Shenyang`, campus:`CN034OF01 Shenyang Shoufu`, building:`SHOUFU`},
    {region:`APAC`, country:`China`, city:`Shanghai`, campus:`CN035OF01 Shanghai Dobehongqiao`, building:`DOBEHONGQIAO`},
    {region:`Americas`, country:`Colombia`, city:`Bogota`, campus:`CO003OF01 CG EDIFICIOTORRE`, building:`EDIFICIOTORRE`},
    {region:`Europe`, country:`Czech Republic`, city:`Praha`, campus:`CZ008OF01 Praha Mayhouse`, building:`MAYHOUSE`},
    {region:`Europe`, country:`Germany`, city:`Berlin`, campus:`DE001OF01 Berlin Potsdame`, building:`POTSDAME`},
    {region:`Europe`, country:`Germany`, city:`Donauwörth`, campus:`DE009OF01 Donauworth Boelkow`, building:`BOELKOW`},
    {region:`Europe`, country:`Germany`, city:`Hamburg`, campus:`DE032OF01 Hamburg Luebecker`, building:`LUEBECKER`},
    {region:`Europe`, country:`Germany`, city:`Hamburg`, campus:`DE032OF01 Hamburg Luebecker (SG)`, building:`LUEBECKER`},
    {region:`Europe`, country:`Germany`, city:`Hamburg`, campus:`DE045OF01 Hamburg Heinsass26`, building:`HEINSASS26`},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE046OF01 Munchen Olofpalm`, building:`OLOFPALM`},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE046OF01 Munchen Olofpalm (SG)`, building:`OLOFPALM`},
    {region:`Europe`, country:`Germany`, city:`Lübeck`, campus:`DE049OF01 Lubeck Ziegel`, building:`ZIEGEL`},
    {region:`Europe`, country:`Germany`, city:`Frankfurt am Main`, campus:`DE052OF01 Frankfurt am Main Mainzer`, building:`MAINZER`},
    {region:`Europe`, country:`Germany`, city:`Frankfurt am Main`, campus:`DE052ST01 Frankfurt Am Main Mainzer`, building:`MAINZER`},
    {region:`Europe`, country:`Germany`, city:`Ratingen`, campus:`DE053OF01 Ratingen Balcke`, building:`BALCKE`},
    {region:`Europe`, country:`Germany`, city:`Ratingen`, campus:`DE053OF01 Ratingen Balcke (SG)`, building:`BALCKE`},
    {region:`Europe`, country:`Germany`, city:`Dortmund`, campus:`DE054OF01 Dortmund Loewens`, building:`LOEWENS`},
    {region:`Europe`, country:`Germany`, city:`Karlsruhe`, campus:`DE057OF01 Karlsruhe Erzbergerstr`, building:`ERZBERGERSTR`},
    {region:`Europe`, country:`Germany`, city:`Nürnberg`, campus:`DE059OF01 Nurnberg Marienzeile`, building:`MARIENZEILE`},
    {region:`Europe`, country:`Germany`, city:`Aalen`, campus:`DE069OF01 Aalen Julusbausch (AL)`, building:`JULUSBAUSCH`},
    {region:`Europe`, country:`Germany`, city:`Berlin`, campus:`DE071OF01 Berlin Moabit98 (AL)`, building:`MOABIT98`},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE074OF01 Munchen Frankfurter (AL)`, building:`FRANKFURTER`},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE075OF01 Munchen Leopold (AL)`, building:`LEOPOLD`},
    {region:`Europe`, country:`Germany`, city:`Bremen`, campus:`DE077OF01 Bremen Airbusallee3 (AL)`, building:`AIRBUSALLEE3`},
    {region:`Europe`, country:`Germany`, city:`Duisburg`, campus:`DE081OF01 Duisburg Wolfgang (AL)`, building:`WOLFGANG`},
    {region:`Europe`, country:`Germany`, city:`Floha`, campus:`DE084OF01 Floha Heinrichheine (AL)`, building:`HEINRICHHEINE`},
    {region:`Europe`, country:`Germany`, city:`Hamburg`, campus:`DE086OF01 Hamburg Heinsass30 (AL)`, building:`HEINSASS`},
    {region:`Europe`, country:`Germany`, city:`Hamburg`, campus:`DE086OF03 Hamburg Heinsass22 (AL)`, building:`HEINSASS`},
    {region:`Europe`, country:`Germany`, city:`Koblenz am Rhein`, campus:`DE090OF01 Koblenz am Rhein Lohrstrasse`, building:`LOHRSTRASSE`},
    {region:`Europe`, country:`Germany`, city:`Koblenz am Rhein`, campus:`DE090OF01 Koblenz am Rhein Lohrstrasse (AL)`, building:`LOHRSTRASSE`},
    {region:`Europe`, country:`Germany`, city:`Marktoberdorf`, campus:`DE093OF01 Marktoberdorf Salzstr (AL)`, building:`SALZSTR`},
    {region:`Europe`, country:`Germany`, city:`Lehre`, campus:`DE095OF01 Lehre Nikolaus (AL)`, building:`NIKOLAUS`},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE097OF01 Munchen Taunusst40 (AL)`, building:`TAUNUSST`},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE097OF02 Munchen Taunusst38 (AL)`, building:`TAUNUSST`},
    {region:`Europe`, country:`Germany`, city:`Weissach`, campus:`DE101OF01 Weissach Buhl11 (AL)`, building:`BUHL11`},
    {region:`Europe`, country:`Germany`, city:`Wimsheim`, campus:`DE102OF01 Wimsheim Daimlerstr (AL)`, building:`DAIMLERSTR`},
    {region:`Europe`, country:`Germany`, city:`Wolfsburg`, campus:`DE105OF01 Wolfsburg Strasse69 (AL)`, building:`STRASSE69`},
    {region:`Europe`, country:`Germany`, city:`Unterschleissheim`, campus:`DE111OF01 Unterschleissheim Edlsonstr (AL)`, building:`EDLSONSTR`},
    {region:`Europe`, country:`Germany`, city:`Stuttgart`, campus:`DE117OF01 Stuttgart Fasanenweg`, building:`FASANENWEG`},
    {region:`Europe`, country:`Germany`, city:`Erfurt`, campus:`DE118OF01 Erfurt Anger`, building:`ANGER`},
    {region:`Europe`, country:`Germany`, city:`Wolfsburg`, campus:`DE120OF01 Wolfsburg Birnbaumstucke (AL)`, building:`BIRNBAUMSTUCKE`},
    {region:`Europe`, country:`Germany`, city:`Hannover`, campus:`DE122OF01 Hannover Podbielskistr`, building:`PODBIELSKISTR`},
    {region:`Europe`, country:`Germany`, city:`Köln`, campus:`DE125OF01 Koln Deutzeralle`, building:`DEUTZERALLE `},
    {region:`Europe`, country:`Germany`, city:`München`, campus:`DE127OF01 Munchen Dr Ludwig`, building:`DETMOLDSTRASSE`},
    {region:`Europe`, country:`Germany`, city:`Gaimersheim`, campus:`DE129OF01 Gaimersheim Detmoldstrasse`, building:`DRLUDWIG`},
    {region:`Americas`, country:`Denmark`, city:`Vallensbæk`, campus:`DK003OF01 Vallensbaek Copenhagen`, building:`COPENHAGEN`},
    {region:`Americas`, country:`Denmark`, city:`Viby`, campus:`DK006OF01 Viby Aarhus`, building:`AARHUS`},
    {region:`Europe`, country:`Spain`, city:`Valencia`, campus:`ES001OF01 Valencia Aragon30`, building:`ARAGON30`},
    {region:`Europe`, country:`Spain`, city:`Barcelona`, campus:`ES009OF01 Barcelona Diagonal199`, building:`DIAGONAL199`},
    {region:`Europe`, country:`Spain`, city:`Barcelona`, campus:`ES009OF01 Barcelona Diagonal199 (AL)`, building:`DIAGONAL199`},
    {region:`Europe`, country:`Spain`, city:`Barcelona`, campus:`ES009OF01 Barcelona Diagonal199 (SG)`, building:`DIAGONAL199`},
    {region:`Europe`, country:`Spain`, city:`La Felguera`, campus:`ES012OF02 La Felguera Incuvatic2`, building:`LAFELGUERA`},
    {region:`Europe`, country:`Spain`, city:`La Felguera`, campus:`ES012OF04 La Felguera Networks`, building:`LAFELGUERA`},
    {region:`Europe`, country:`Spain`, city:`Murcia`, campus:`ES024OF01 Murcia Nelva`, building:`NELVA`},
    {region:`Europe`, country:`Spain`, city:`Madrid`, campus:`ES027OF01 Madrid Oxxeo`, building:`OXXEO`},
    {region:`Europe`, country:`Spain`, city:`Madrid`, campus:`ES027OF01 Madrid Puerto de Somport`, building:`OXXEO`},
    {region:`Europe`, country:`Spain`, city:`Madrid`, campus:`ES028OF01 Madrid Campezo Edificio1 (AL)`, building:`CAMPEZO`},
    {region:`Europe`, country:`Spain`, city:`Madrid`, campus:`ES028OF02 Madrid Campezo Edificio9 (AL)`, building:`CAMPEZO`},
    {region:`Europe`, country:`Spain`, city:`Madrid`, campus:`ES028OF03 Madrid Campezo Edificio4 (AL)`, building:`CAMPEZO`},
    {region:`Europe`, country:`Spain`, city:`San Sebastian`, campus:`ES029OF01 San Sebastian Donostia (AL)`, building:`DONOSTIA`},
    {region:`Europe`, country:`Spain`, city:`Valladolid`, campus:`ES030OF01 Valladolid Calledesantiago (AL)`, building:`CALLEDESANTIAGO`},
    {region:`Europe`, country:`Spain`, city:`Sevilla`, campus:`ES035OF01 Sevilla Hispano (AL)`, building:`HISPANO`},
    {region:`Europe`, country:`Spain`, city:`Cadiz`, campus:`ES036OF01 Cadiz Callefrancia (AL)`, building:`CALLEFRANCIA`},
    {region:`Europe`, country:`Spain`, city:`Vitoria-Gasteiz`, campus:`ES038OF01 Vitoria-Gasteiz Aekalea (AL)`, building:`AEKALEA`},
    {region:`Europe`, country:`Spain`, city:`Sant Esteve Sesrovires`, campus:`ES041OF01 Sant Esteve Sesrovires Galileu (AL)`, building:`GALILEU`},
    {region:`Europe`, country:`Spain`, city:`Málaga`, campus:`ES045OF01 Malaga Malagatechpark`, building:`MALAGATECHPARK`},
    {region:`Americas`, country:`Finland`, city:`Lappeenranta (Villmanstrand)`, campus:`FI003OF01 Lappeenranta Laserkatu`, building:`LAPPEENRANTA`},
    {region:`Americas`, country:`Finland`, city:`Helsinki (Helsingfors)`, campus:`FI014OF01 Helsinki Helsingfors`, building:`HELSINKI`},
    {region:`France`, country:`France`, city:`Vernon`, campus:`FR001OF01 Vernon Hubert Curien`, building:`VERNON`},
    {region:`France`, country:`France`, city:`Brest`, campus:`FR003OF01 Brest Malbert`, building:`MALBERT`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR004OF01 Paris Provence`, building:`PROVENCE`},
    {region:`France`, country:`France`, city:`Orléans`, campus:`FR006OF01 Orleans Emilezolaorlean`, building:`EMILEZOLAORLEAN`},
    {region:`France`, country:`France`, city:`Schiltigheim`, campus:`FR008OF01 Schiltigheim Lahaye`, building:`LAHAYE`},
    {region:`France`, country:`France`, city:`Ruoms`, campus:`FR009OF01 Ruoms Gare`, building:`GARE`},
    {region:`France`, country:`France`, city:`Mérignac`, campus:`FR012OF01 Merignac Jameswatt`, building:`JAMESWATT`},
    {region:`France`, country:`France`, city:`Issy-les-Moulineaux`, campus:`FR013OF02 Issy-Les-Moulineaux Axium HTC`, building:`AXIUM`},
    {region:`France`, country:`France`, city:`Mâcon`, campus:`FR014OF01 Boulevard Macon`, building:`MACON`},
    {region:`France`, country:`France`, city:`Toulouse`, campus:`FR018OF01 Toulouse B612`, building:`B612`},
    {region:`France`, country:`France`, city:`Bayonne`, campus:`FR027OF01 Bayonne Batastria`, building:`BATASTRIA`},
    {region:`France`, country:`France`, city:`Toulouse`, campus:`FR033OF01 Toulouse Perroud`, building:`PERROUD`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR034OF01 Paris Trevise`, building:`TREVISE`},
    {region:`France`, country:`France`, city:`Niort`, campus:`FR042OF01 Niort Marais`, building:`MARAIS`},
    {region:`France`, country:`France`, city:`Montbonnot-Saint-Martin`, campus:`FR052OF01 Montbonnot-Saint-Martin 95`, building:`MONTBONNOT`},
    {region:`France`, country:`France`, city:`Montbonnot-Saint-Martin`, campus:`FR052OF02 Montbonnot-Saint-Martin 99`, building:`MONTBONNOT`},
    {region:`France`, country:`France`, city:`Dompierre-sur-Mer`, campus:`FR058OF01 Dompierre-sur-Mer Dompierre`, building:`DOMPIERRE`},
    {region:`France`, country:`France`, city:`Melun`, campus:`FR082OF01 Melun Liberation`, building:`LIBERATION`},
    {region:`France`, country:`France`, city:`Pérols`, campus:`FR088OF01 Perols Concorde`, building:`CONCORDE`},
    {region:`France`, country:`France`, city:`Bordes`, campus:`FR090OF01 Bordes Poleaero`, building:`POLEAERO`},
    {region:`France`, country:`France`, city:`Toulouse`, campus:`FR114OF01 Toulouse Aeropark`, building:`AEROPARK`},
    {region:`France`, country:`France`, city:`Cesson-Sévigné`, campus:`FR121OF01 Cesson-Sevigne Spirea`, building:`SPIREA`},
    {region:`France`, country:`France`, city:`Nantes`, campus:`FR122OF01 Nantes Axeo`, building:`AXEO`},
    {region:`France`, country:`France`, city:`Chantilly`, campus:`FR124OF01 Chantilly Fontaines`, building:`FONTAINES`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR127OF01 Paris Kleber`, building:`KLEBER`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR128OF01 Paris Tilsitt`, building:`TILSITT`},
    {region:`France`, country:`France`, city:`Nancy`, campus:`FR130OF01 Nancy Cardinal`, building:`CARDINAL`},
    {region:`France`, country:`France`, city:`Toulouse`, campus:`FR131OF01 Toulouse Eisenhower`, building:`EISENHOWER`},
    {region:`France`, country:`France`, city:`Schiltigheim`, campus:`FR132OF01 Schiltigheim Copenhague`, building:`COPENHAGUE`},
    {region:`France`, country:`France`, city:`Bagnols-sur-Cèze`, campus:`FR150OF01 Bagnols-Sur-Ceze Zadeleuze`, building:`ZADELEUZE`},
    {region:`France`, country:`France`, city:`Beaumont-Hague`, campus:`FR156OF01 Beaumont-Hague Diganc`, building:`DIGANC`},
    {region:`France`, country:`France`, city:`Cherbourg-en-Cotentin`, campus:`FR159OF01 Cherbourg-en-Cotentin Tourville23`, building:`EQUXXTOURV`},
    {region:`France`, country:`France`, city:`Cherbourg-en-Cotentin`, campus:`FR159OF02 Cherbourg-en-Cotentin Tourville25`, building:`EQUXXTOURV`},
    {region:`France`, country:`France`, city:`Pau`, campus:`FR176OF01 Pau Newtonpau`, building:`NEWTONPAU`},
    {region:`France`, country:`France`, city:`Lyon`, campus:`FR178OF01 Lyon Ivoire`, building:`IVOIRE`},
    {region:`France`, country:`France`, city:`Aix-en-Provence`, campus:`FR181OF01 Aix-en-Provence Parcdugolf`, building:`PARCDUGOLF`},
    {region:`France`, country:`France`, city:`Issy-les-Moulineaux`, campus:`FR183OF01 Issy-les-Moulineaux Juin`, building:`JUIN`},
    {region:`France`, country:`France`, city:`Bourogne`, campus:`FR184OF01 Bourogne Lajonxion`, building:`LAJONXION`},
    {region:`France`, country:`France`, city:`Nantes`, campus:`FR185OF01 Nantes Berlingot`, building:`BERLINGOT`},
    {region:`France`, country:`France`, city:`Aubière`, campus:`FR186OF01 Aubiere Lapardieu`, building:`LAPARDIEU`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR187OF01 Paris Cambaceres (PR)`, building:`CAMBACERES`},
    {region:`France`, country:`France`, city:`Lille`, campus:`FR190OF01 Lille Greentech`, building:`GREENTECH`},
    {region:`France`, country:`France`, city:`Issy-les-Moulineaux`, campus:`FR192OF01 Issy-les-Moulineaux Marceau`, building:`MARCEAU`},
    {region:`France`, country:`France`, city:`Issy-les-Moulineaux`, campus:`FR193OF01 Issy-les-Moulineaux 147`, building:`147`},
    {region:`France`, country:`France`, city:`Blagnac`, campus:`FR197OF01 Blagnac Aeropole`, building:`AEROPOLE`},
    {region:`France`, country:`France`, city:`Saint-Ouen`, campus:`FR202OF01 Saint-Ouen Ruealbert (AL)`, building:`RUEALBERT`},
    {region:`France`, country:`France`, city:`Blagnac`, campus:`FR206OF01 Blagnac Didierdaurat (AL)`, building:`DIDIERDAURAT`},
    {region:`France`, country:`France`, city:`Blagnac`, campus:`FR206OF02 Blagnac Didierdaurat (AL)`, building:`DIDIERDAURAT`},
    {region:`France`, country:`France`, city:`Cormelles-le-Royal`, campus:`FR209OF01 Cormelles-Le-Royal Ruemetiers (AL)`, building:`RUEMETIERS`},
    {region:`France`, country:`France`, city:`Chavanod`, campus:`FR211OF01 Chavanod Ruecassiopee (AL)`, building:`RUECASSIOPEE`},
    {region:`France`, country:`France`, city:`Illkirch-Graffenstaden`, campus:`FR213OF01 Illkirch-Graffenstaden Leparc (AL)`, building:`LEPARC`},
    {region:`France`, country:`France`, city:`Le Havre`, campus:`FR214OF01 Le Havre Saintnicolas (AL)`, building:`SAINTNICOLAS`},
    {region:`France`, country:`France`, city:`Lons`, campus:`FR216OF01 Lons Pierregilles (AL)`, building:`PIERREGILLES`},
    {region:`France`, country:`France`, city:`Dunkerque`, campus:`FR223OF01 Dunkerque Universite (AL)`, building:`UNIVERSITE`},
    {region:`France`, country:`France`, city:`Marseille`, campus:`FR225OF01 Marseille Michelet (AL)`, building:`MICHELET`},
    {region:`France`, country:`France`, city:`Massy`, campus:`FR227OF01 Massy Desfemmes (AL)`, building:`DESFEMMES`},
    {region:`France`, country:`France`, city:`Maxéville`, campus:`FR230OF01 Maxeville Oceanis (AL)`, building:`OCEANIS4`},
    {region:`France`, country:`France`, city:`Méaulte`, campus:`FR231OF01 Meaulte Rogerjanin (AL)`, building:`ROGERJANIN`},
    {region:`France`, country:`France`, city:`Metz`, campus:`FR236OF01 Metz Solidarite (AL)`, building:`SOLIDARITE`},
    {region:`France`, country:`France`, city:`Pérols`, campus:`FR242OF01 Perols Georgesfrche (AL)`, building:`GEORGESFRCHE`},
    {region:`France`, country:`France`, city:`Pierrelatte`, campus:`FR243OF01 Pierrelatte Paulsabatier (AL)`, building:`PAULSABATIER`},
    {region:`France`, country:`France`, city:`Rennes`, campus:`FR244OF01 Rennes De Lorient (AL)`, building:`DEORIENT`},
    {region:`France`, country:`France`, city:`Rennes`, campus:`FR244OF02 Rennes De Lorient (AL)`, building:`DEORIENT`},
    {region:`France`, country:`France`, city:`Serris`, campus:`FR246OF01 Serris Coursdudanube (AL)`, building:`COURSDUDANUBE`},
    {region:`France`, country:`France`, city:`Valenciennes`, campus:`FR248OF01 Valenciennes Lefranc (AL)`, building:`LEFRANC`},
    {region:`France`, country:`France`, city:`Vitrolles`, campus:`FR250OF01 Vitrolles Estroublans (AL)`, building:`ESTROUBLANS`},
    {region:`France`, country:`France`, city:`Saint-Herblain`, campus:`FR252OF01 Saint-Herblain Impassecharles (AL)`, building:`IMPASSECHARLES`},
    {region:`France`, country:`France`, city:`Lure`, campus:`FR255OF01 Lure Ruedescloies (AL)`, building:`RUEDESCLOIES`},
    {region:`France`, country:`France`, city:`Dijon`, campus:`FR259OF01 Dijon Proactive (AL)`, building:`PROACTIVE`},
    {region:`France`, country:`France`, city:`Aix-en-Provence`, campus:`FR260OF01 Aix-En-Provence Immeuble (AL)`, building:`IMMEUBLE`},
    {region:`France`, country:`France`, city:`Les Mureaux`, campus:`FR261OF01 Les Mureaux Pierrecurie (AL)`, building:`142PIERRECURIE`},
    {region:`France`, country:`France`, city:`Isneauville`, campus:`FR263OF01 Isneauville Francoisjacob`, building:`FRANCOISJACOB`},
    {region:`France`, country:`France`, city:`Meudon`, campus:`FR266OF01 Meudon Mcampus`, building:`MCAMPUS`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR267OF01 Paris Morningboissier (AL)`, building:`MORNINGBOISSIER`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR268OF01 Paris Bastille`, building:`BASTILLE`},
    {region:`France`, country:`France`, city:`Saint-Pierre-des-Corps`, campus:`FR269OF01 Saint-Pierre-Des-Corps 31Flandy`, building:`31FLANDY`},
    {region:`France`, country:`France`, city:`Plouzané`, campus:`FR270OF01 Plouzane Plouzane (AL)`, building:`PLOUZANE`},
    {region:`France`, country:`France`, city:`Bièvres`, campus:`FR271OF01 Bievres BAT26BUROSPACE (AL)`, building:`BAT26BUROSPACE`},
    {region:`France`, country:`France`, city:`Marseille`, campus:`FR272OF01 Marseille Hiptown (AL)`, building:`HIPTOWN`},
    {region:`France`, country:`France`, city:`Issy-les-Moulineaux`, campus:`FR273OF01 Issy-Les-Moulineaux Startway (AL)`, building:`STARTWAY`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR275OF01 Paris FUTURE4CARE`, building:`FUTURE4CARE`},
    {region:`France`, country:`France`, city:`Puteaux`, campus:`FR276OF01 Puteaux CYBER CAMPUS`, building:`CAMPUS CYBER`},
    {region:`France`, country:`France`, city:`Le Bourget-du-Lac`, campus:`FR278OF01 Le Bourget-du-Lac LEVILLAGE`, building:`LEVILLAGE`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR280OF01 Paris ROYALE`, building:`ROYALE`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR281 CG Aix-en-Provence-Aurore`, building:`ANJOU`},
    {region:`France`, country:`France`, city:`Paris`, campus:`FR281OF01 CG Paris ANJOU`, building:`ANJOU`},
    {region:`France`, country:`France`, city:`Valbonne`, campus:`FR284OF01 Valbonne Sophia`, building:`VALBONNE`},
    {region:`Europe`, country:`United Kingdom`, city:`London`, campus:`GB007OF01 London Holborn`, building:`HOLBORN`},
    {region:`Europe`, country:`United Kingdom`, city:`Liverpool`, campus:`GB010OF01 Liverpool Horton House`, building:`HORTON`},
    {region:`Europe`, country:`United Kingdom`, city:`Nairn`, campus:`GB014OF01 Nairn Balmakeith`, building:`NAIRN`},
    {region:`Europe`, country:`United Kingdom`, city:`Telford`, campus:`GB024OF01 Telford International House`, building:`TELFORDIHOUSE`},
    {region:`Europe`, country:`United Kingdom`, city:`Telford`, campus:`GB025OF01 Telford Telford Matheson House`, building:`TELFORDMATHESON`},
    {region:`Europe`, country:`United Kingdom`, city:`Woking`, campus:`GB035OF01 Woking Forge End`, building:`WOKING`},
    {region:`Europe`, country:`United Kingdom`, city:`Inverness`, campus:`GB050OF01 Inverness Cowan House`, building:`COWAN`},
    {region:`Europe`, country:`United Kingdom`, city:`Pontypridd`, campus:`GB054OF01 Pontypridd Treforest Wales`, building:`TREFOREST`},
    {region:`Europe`, country:`United Kingdom`, city:`London`, campus:`GB061OF01 London Victoria House`, building:`LEONARDCIRCUS`},
    {region:`Europe`, country:`United Kingdom`, city:`Manchester`, campus:`GB066OF01 Manchester Venus`, building:`MANCHESTER`},
    {region:`Europe`, country:`United Kingdom`, city:`Bath`, campus:`GB068OF01 Bath Southgate (AL)`, building:`SOUTHGATE`},
    {region:`Europe`, country:`United Kingdom`, city:`Newbury`, campus:`GB070OF01 Newbury Peartreehouse (AL)`, building:`PEARTREEHOUSE`},
    {region:`Europe`, country:`United Kingdom`, city:`Bristol`, campus:`GB071OF01 Bristol Brabazon OF Park (AL)`, building:`BRABAZONOFPARK`},
    {region:`Europe`, country:`United Kingdom`, city:`Abingdon`, campus:`GB077OF01 Abingdon The Quadrant (AL)`, building:`ABINGDON`},
    {region:`Europe`, country:`United Kingdom`, city:`Ashby de la Zouch`, campus:`GB078OF01 Ashby De La Zouch Ashby (AL)`, building:`ASHBY`},
    {region:`Europe`, country:`United Kingdom`, city:`Stevenage`, campus:`GB079OF01 Stevenage Richmond House (AL)`, building:`STEVENAGE`},
    {region:`Europe`, country:`United Kingdom`, city:`Warrington`, campus:`GB080OF01 Warrington Birchwood Park (AL)`, building:`WARRINGTON`},
    {region:`Europe`, country:`United Kingdom`, city:`Cambridge`, campus:`GB081OF01 Cambridge Cambridgescpark Unit 29 (AL)`, building:`CAMBRIDGESCPARK`},
    {region:`Europe`, country:`United Kingdom`, city:`Cambridge`, campus:`GB081OF01 Cambridge Cambridgescpark Unit 300 (AL)`, building:`CAMBRIDGESCPARK`},
    {region:`Europe`, country:`United Kingdom`, city:`Worthing`, campus:`GB089OF01 Worthing Durrington`, building:`WORTHING`},
    {region:`Europe`, country:`United Kingdom`, city:`Newbury`, campus:`GB090OF01 Newbury Bedfordhouse (AL)`, building:`BEDFORDHOUSE`},
    {region:`Europe`, country:`United Kingdom`, city:`Glasgow`, campus:`GB096OF01 WRS Glasgow`, building:`WRSGLASGOW`},
    {region:`Americas`, country:`Guatemala`, city:`Guatemala City`, campus:`GT002OF01 Guatemala City Wtc`, building:`WTC`},
    {region:`APAC`, country:`Hong Kong`, city:`Hong Kong`, campus:`HK002OF01 Hong Kong One Island East`, building:`ONEISLANDEAST`},
    {region:`Europe`, country:`Hungary`, city:`Budapest`, campus:`HU001OF01 Budapest Budawest`, building:`BUDAWEST`},
    {region:`Other Countries`, country:`Ireland`, city:`Dublin`, campus:`IE003OF01 Dublin Metropolitan`, building:`METROPOLITAN`},
    {region:`Europe`, country:`Italy`, city:`Bologna`, campus:`IT006OF01 Bologna Faggiolo`, building:`FAGGIOLO`},
    {region:`Europe`, country:`Italy`, city:`Marcon`, campus:`IT009OF01 Marcon Mattei`, building:`MATTEI`},
    {region:`Europe`, country:`Italy`, city:`Piacenza`, campus:`IT010OF01 Piacenza Modonesi`, building:`MODONESI`},
    {region:`Europe`, country:`Italy`, city:`Rome (Roma)`, campus:`IT018OF01 Rome Torrespac`, building:`TORRESPAC`},
    {region:`Europe`, country:`Italy`, city:`La Spezia`, campus:`IT022OF01 La Spezia Vailunga`, building:`VAILUNGA`},
    {region:`Europe`, country:`Italy`, city:`Napoli`, campus:`IT029OF01 Napoli Palazzoalt`, building:`PALAZZOALT`},
    {region:`Europe`, country:`Italy`, city:`Torino`, campus:`IT032OF01 Torino Drosso (AL)`, building:`DROSSO`},
    {region:`Europe`, country:`Italy`, city:`Genova`, campus:`IT040OF01 Genova Settembre (AL)`, building:`SETTEMBRE`},
    {region:`Europe`, country:`Italy`, city:`Modena`, campus:`IT043OF01 Modena Marcello (AL)`, building:`MARCELLO`},
    {region:`Europe`, country:`Italy`, city:`Pomigliano D'Arco`, campus:`IT046OF01 Pomigliano D'Arco Luraghi (AL)`, building:`LURAGHI`},
    {region:`Europe`, country:`Italy`, city:`Rome (Roma)`, campus:`IT057OF01 Rome Aldobrandeschi`, building:`ALDOBRANDESCHI`},
    {region:`Europe`, country:`Italy`, city:`Milano`, campus:`IT058OF01 Milano Pharo`, building:`PHARO`},
    {region:`APAC`, country:`Japan`, city:`Tokyo`, campus:`JP004OF01 Tokyo Toranomon`, building:`TORANOMON`},
    {region:`APAC`, country:`Japan`, city:`Tokyo`, campus:`JP007OF01 Tokyo Minamiaoyama (AL)`, building:`MINAMIAOYAMA`},
    {region:`APAC`, country:`Japan`, city:`Tsukuba`, campus:`JP008OF01 Tsukuba Tsukuba`, building:`TSUKUBA `},
    {region:`Europe`, country:`Luxembourg`, city:`Bertrange`, campus:`LU002OF01 Bertrange Longwy`, building:`BERTRANGE`},
    {region:`Europe`, country:`Morocco`, city:`Rabat`, campus:`MA001OF01 Rabat Rabatsale B7`, building:`RABATSALE`},
    {region:`Europe`, country:`Morocco`, city:`Casablanca`, campus:`MA002 CG Shore 8`, building:`ALQUODS`},
    {region:`Europe`, country:`Morocco`, city:`Casablanca`, campus:`MA002OF01 Casablanca Alquods`, building:`ALQUODS`},
    {region:`Europe`, country:`Morocco`, city:`Casablanca`, campus:`MA004OF01 Casablanca Casanearshore (AL)`, building:`CASANEARSHORE`},
    {region:`Americas`, country:`Mexico`, city:`Aguascalientes`, campus:`MX007OF01 Aguascalientes Zaragoza`, building:`AGUASCALIENTES`},
    {region:`Americas`, country:`Mexico`, city:`Guadalajara`, campus:`MX010OF01 Guadalajara Zapopan (AL)`, building:`ZAPOPAN`},
    {region:`APAC`, country:`Malaysia`, city:`Kuala Lumpur`, campus:`MY001OF01 Kuala Lumpur Kualalumpur`, building:`KUALALUMPUR`},
    {region:`Europe`, country:`Netherlands`, city:`Groningen`, campus:`NL011 CG Groningen1`, building:`GRONSOGETI`},
    {region:`Europe`, country:`Netherlands`, city:`Groningen`, campus:`NL011OF01 Groningen GronSogeti`, building:`GRONSOGETI`},
    {region:`Europe`, country:`Netherlands`, city:`Heerlen`, campus:`NL013OF01 Heerlen Vogt`, building:`HEERLEN`},
    {region:`Europe`, country:`Netherlands`, city:`Utrecht`, campus:`NL022OF01 Reykjavikplein Utrecht`, building:`UTRECHTLR`},
    {region:`Europe`, country:`Netherlands`, city:`Amsterdam`, campus:`NL028OF01 Amsterdam Vogelstr`, building:`VOGELSTR`},
    {region:`Europe`, country:`Netherlands`, city:`Amsterdam`, campus:`NL028OF01 Amsterdam Vogelstr (SG)`, building:`VOGELSTR`},
    {region:`Europe`, country:`Netherlands`, city:`Capelle aan den IJssel`, campus:`NL029OF01 Capelle aan den IJssel Rotterdamsog`, building:`ROTTERDAMSOG`},
    {region:`Europe`, country:`Netherlands`, city:`Eindhoven`, campus:`NL037OF01 Limburglaan Eindhoven (AL)`, building:`EINDHOVENLIMBUR`},
    {region:`Europe`, country:`Netherlands`, city:`Hengelo`, campus:`NL039OF01 Hengelo Haaksbergerstraat (AL)`, building:`HENGELO`},
    {region:`Europe`, country:`Netherlands`, city:`Zwolle`, campus:`NL044OF02 Zwolle Hanzelaan (AL)`, building:`ZWOLLE`},
    {region:`Americas`, country:`Norway`, city:`Fredrikstad`, campus:`NO003OF01 Fredrikstad Krakeroyveien`, building:`FREDRIKSTAD`},
    {region:`Americas`, country:`Norway`, city:`Stavanger`, campus:`NO005OF01 Stavanger Maskinveien`, building:`STAVANGER`},
    {region:`Americas`, country:`Norway`, city:`Oslo`, campus:`NO008 SG Oslo Sjolyst Plass`, building:`OSLO`},
    {region:`Americas`, country:`Norway`, city:`Oslo`, campus:`NO008OF01 Oslo Karenslyst Alle1`, building:`OSLO`},
    {region:`Americas`, country:`Norway`, city:`Bergen`, campus:`NO014OF01 Bergen Krinkelkroken`, building:`BERGEN`},
    {region:`Americas`, country:`Norway`, city:`Sandefjord`, campus:`NO018OF01 Sandefjord Nordrekullerod`, building:`NORDREKULLEROD`},
    {region:`Americas`, country:`Norway`, city:`Trondheim`, campus:`NO024OF01 Trondheim Captrondheim`, building:`CAPTRONDHEIM`},
    {region:`Americas`, country:`Norway`, city:`Kristiansand`, campus:`NO025OF01 Kristiansand Vestre Office`, building:`VESTREOFFICE`},
    {region:`Other Countries`, country:`New Zealand`, city:`Dunedin`, campus:`NZ003OF01 Dunedin Willow Bank`, building:`WILLOWBANK`},
    {region:`Other Countries`, country:`New Zealand`, city:`Auckland`, campus:`NZ004OF01 Auckland Fanshawe Street`, building:`FANSHAWESTREET`},
    {region:`Other Countries`, country:`New Zealand`, city:`Wellington`, campus:`NZ005OF01 Wellington Willis Street`, building:`WILLISSTREET`},
    {region:`Other Countries`, country:`New Zealand`, city:`Christchurch`, campus:`NZ006OF01 Christchurch Unimed House`, building:`UNIMEDHOUSE`},
    {region:`APAC`, country:`Philippines`, city:`Manila`, campus:`PH003OF01 Manila Tenwestcampus`, building:`TENWESTCAMPUS`},
    {region:`Europe`, country:`Poland`, city:`Poznan`, campus:`PL015OF01 Poznan Business Garden`, building:`BUSINESSGARDEN`},
    {region:`Europe`, country:`Poland`, city:`Opole`, campus:`PL016OF01 Opole OCO`, building:`OCO`},
    {region:`Europe`, country:`Poland`, city:`Wroclaw`, campus:`PL017OF01 Wroclaw Business Garden H`, building:`BUSINESSGARDEN`},
    {region:`Europe`, country:`Poland`, city:`Wroclaw`, campus:`PL017OF02 Wroclaw Business Garden K`, building:`BUSINESSGARDEN`},
    {region:`Europe`, country:`Poland`, city:`Warszawa`, campus:`PL018OF01 Warszawa Business Garden`, building:`BUSINESSGARDEN`},
    {region:`Europe`, country:`Poland`, city:`Katowice`, campus:`PL020OF02 Katowice Face2Face B`, building:`FACE2FACE`},
    {region:`Europe`, country:`Poland`, city:`Lublin`, campus:`PL021OF01 Lublin Office Park`, building:`OFFICEPARK`},
    {region:`Europe`, country:`Poland`, city:`Krakow`, campus:`PL023OF01 Krakow Fabryczna`, building:`FABRYCZNA`},
    {region:`Europe`, country:`Portugal`, city:`Lisboa`, campus:`PT001OF01 Lisboa Colombo`, building:`COLOMBO`},
    {region:`Europe`, country:`Portugal`, city:`Évora`, campus:`PT002OF01 Evora Somefe`, building:`SOMEFE`},
    {region:`Europe`, country:`Portugal`, city:`Lisboa`, campus:`PT003OF01 Lisboa Expo Office (AL)`, building:`EXPOOFFICE`},
    {region:`Europe`, country:`Portugal`, city:`Fundão`, campus:`PT004OF01 Fundao Fundao Office (AL)`, building:`FUNDAOOFFICE`},
    {region:`Europe`, country:`Portugal`, city:`Vila Nova de Gaia`, campus:`PT005OF01 Gaia Cais de Gaia (AL)`, building:`CAISDEGAIA`},
    {region:`Europe`, country:`Portugal`, city:`Vila Nova de Gaia`, campus:`PT006OF01 Vila Nova De Gaia Lake Towers (AL)`, building:`LAKETOWERS`},
    {region:`Europe`, country:`Romania`, city:`Iasi`, campus:`RO002OF01 Iasi Palas`, building:`PALAS`},
    {region:`Europe`, country:`Romania`, city:`Bucharest`, campus:`RO005OF01 Bucharest Greencourt`, building:`GREENCOURT`},
    {region:`Europe`, country:`Romania`, city:`Cluj-Napoca`, campus:`RO008OF01 Cluj-Napoca Gariist (AL)`, building:`GARIIST`},
    {region:`Europe`, country:`Romania`, city:`Brasov`, campus:`RO009OF01 Brasov Coresi (AL)`, building:`CORESI`},
    {region:`Americas`, country:`Sweden`, city:`Borlänge`, campus:`SE004OF01 Borlange Borlange (SG)`, building:`BORLANGE`},
    {region:`Americas`, country:`Sweden`, city:`Jönköping`, campus:`SE009OF01 Jonkoping Jonkopingsog (SG)`, building:`JONKOPINGSOG`},
    {region:`Americas`, country:`Sweden`, city:`Gävle`, campus:`SE013OF01 Gavle Gavle (SG)`, building:`GAVLE`},
    {region:`Americas`, country:`Sweden`, city:`Linköping`, campus:`SE015OF01 Linkoping Linkoping (SG)`, building:`LINKOPING`},
    {region:`Americas`, country:`Sweden`, city:`Helsingborg`, campus:`SE021OF01 Helsingborg Helsingborgcap`, building:`HELSINGBORGCAP`},
    {region:`Americas`, country:`Sweden`, city:`Växjö`, campus:`SE027OF01 Vaxjo Vaxjo`, building:`VAXJO`},
    {region:`Americas`, country:`Sweden`, city:`Örnsköldsvik`, campus:`SE028OF01 Ornskoldsvik Ornskoldsvik (SG)`, building:`ORNSKOLDSVIK`},
    {region:`Americas`, country:`Sweden`, city:`Solna`, campus:`SE032OF01 Solna Svetsarvagen (SG)`, building:`SOLNA`},
    {region:`Americas`, country:`Sweden`, city:`Karlstad`, campus:`SE034OF01 Karlstad Vaxnasgatan (SG)`, building:`KARLSTAD`},
    {region:`Americas`, country:`Sweden`, city:`Älmhult`, campus:`SE035OF01 Almhult Almhult`, building:`ALMHULT`},
    {region:`Americas`, country:`Sweden`, city:`Malmö`, campus:`SE037OF01 Malmo Hyllie`, building:`HYLLIE`},
    {region:`Americas`, country:`Sweden`, city:`Nyköping`, campus:`SE038OF01 Nykoping Nykoping (SG)`, building:`NYKOPING`},
    {region:`Americas`, country:`Sweden`, city:`Göteborg`, campus:`SE039OF01 Goteborg Gothenburg`, building:`GOTHENBURG`},
    {region:`Americas`, country:`Sweden`, city:`Umeå`, campus:`SE041OF01 Umea Umea (SG)`, building:`UMEA`},
    {region:`Americas`, country:`Sweden`, city:`Stockholm`, campus:`SE044OF01 Stockholm Felminggatan`, building:`STOCKHOLM`},
    {region:`Americas`, country:`Sweden`, city:`Luleå`, campus:`SE045OF01 Lulea Lulea (SG)`, building:`LULEA`},
    {region:`Americas`, country:`Sweden`, city:`Malmö`, campus:`SE047OF02 Malmo Malmo`, building:`MALMO`},
    {region:`Americas`, country:`Sweden`, city:`Göteborg`, campus:`SE053OF01 Goteborg Arkaden (AL)`, building:`ARKADEN`},
    {region:`Americas`, country:`Sweden`, city:`Karlstad`, campus:`SE055OF01 Karlstad Tullhusgatan (AL)`, building:`TULLHUSGATAN`},
    {region:`Americas`, country:`Sweden`, city:`Västerås`, campus:`SE061OF01 Vasteras Port Anders Gata 9 (SG)`, building:`VASTERASSOGETI`},
    {region:`Americas`, country:`Sweden`, city:`Malmö`, campus:`SE067OF01 Malmo Tullhuset (AL)`, building:`TULLHUSET`},
    {region:`Americas`, country:`Sweden`, city:`Östersund`, campus:`SE068OF01 Istersund Prastgatan`, building:`PRASTGATAN`},
    {region:`Americas`, country:`Sweden`, city:`Härnösand`, campus:`SE069OF01 Harnosand Harnosand`, building:`HARNOSAND`},
    {region:`Americas`, country:`Sweden`, city:`Uppsala`, campus:`SE070OF01 Uppsala Dragarbrunn`, building:`DRAGARBRUNN`},
    {region:`Americas`, country:`Sweden`, city:`Helsingborg`, campus:`SE071OF01 Helsingborg regula 1`, building:`REGULA1`},
    {region:`Americas`, country:`Sweden`, city:`Skellefteå`, campus:`SE072OF01 Kanalgatan Skelleftea`, building:`KANALGATAN`},
    {region:`Americas`, country:`Sweden`, city:`Sundsvall`, campus:`SE073OF01 Bankgatan Sundsvall`, building:`BANKGATAN`},
    {region:`Americas`, country:`Sweden`, city:`Örebro`, campus:`SE074OF01 Orebro Fabriksgatan`, building:`FABRIKSGATAN`},
    {region:`APAC`, country:`Singapore`, city:`Singapore`, campus:`SG003OF01 Singapore Marinaboulevard`, building:`MARINABOULEVARD`},
    {region:`APAC`, country:`Singapore`, city:`Singapore`, campus:`SG004OF01 Singapore Concourse (AL)`, building:`CONCOURSE`},
    {region:`Europe`, country:`Slovakia`, city:`Trnava`, campus:`SK002OF01 Trnava Bcaquapolis`, building:`BCAQUAPOLIS`},
    {region:`Other Countries`, country:`Ukraine`, city:`Odesa`, campus:`UA001OF01 Odesa Bunina St. (AL)`, building:`BUNINAST`},
    {region:`Europe`, country:`Ukraine`, city:`Rivne`, campus:`UA004OF01 Rivne Soborna St. (AL)`, building:`SOBORNAST`},
    {region:`Europe`, country:`Ukraine`, city:`Kiev`, campus:`UA006OF01 Kyiv Europassage (AL)`, building:`EUROPASSAGE`},
    {region:`Europe`, country:`Ukraine`, city:`L'viv`, campus:`UA007OF01 Lviv Bcviking`, building:`BCVIKING`},
    {region:`Americas`, country:`United States`, city:`Tampa`, campus:`US003OF01 Tampa Ashleysog (SG)`, building:`ASHLEYSOG`},
    {region:`Americas`, country:`United States`, city:`Atlanta`, campus:`US028OF01 Atlanta Buckkhd`, building:`BUCKKHD`},
    {region:`Americas`, country:`United States`, city:`Cincinnati`, campus:`US035OF01 Cincinnati Lakeforsog (SG)`, building:`LAKEFORSOG`},
    {region:`Americas`, country:`United States`, city:`Chicago`, campus:`US076OF01 Chicago 333Wwacker`, building:`333WWACKER`},
    {region:`Americas`, country:`United States`, city:`Austin`, campus:`US082OF01 Austin Techridgepark`, building:`TECHRIDGEPARK`},
    {region:`Americas`, country:`United States`, city:`Houston`, campus:`US083OF01 Houston Westhmr`, building:`WESTHMR`},
    {region:`Americas`, country:`United States`, city:`McLean/Washington, D.C.`, campus:`US108OF01 McLean/Washington, D.C. Greensboro`, building:`GREENSBORO`},
    {region:`Americas`, country:`United States`, city:`New York`, campus:`US110OF01 New York 79Fifthave`, building:`79FIFTHAVE`},
    {region:`Americas`, country:`United States`, city:`Columbia`, campus:`US121OF01 Columbia 2142Boyce`, building:`2142BOYCE`},
    {region:`Americas`, country:`United States`, city:`Irving`, campus:`US156OF01 Irving Williamssquare`, building:`WILLIAMSSQUARE`},
    {region:`Americas`, country:`United States`, city:`Rockville`, campus:`US168OF01 Rockville Montgomery Avenue (AL)`, building:`ROCKVILLE`},
    {region:`Americas`, country:`United States`, city:`Santa Clara`, campus:`US169OF01 Santa Clara Freedomcircle (AL)`, building:`FREEDOMCIRCLE`},
    {region:`Americas`, country:`United States`, city:`Brooklyn/New York`, campus:`US183OF01 New York Prospectstreet (AL)`, building:`PROSPECTSTREET`},
    {region:`Americas`, country:`United States`, city:`San Francisco`, campus:`US185OF01 San Francisco Howardstreet (AL)`, building:`HOWARDSTREET`},
    {region:`Americas`, country:`United States`, city:`Seattle`, campus:`US189OF01 Seattle 6Thavenue (AL)`, building:`6THAVENUE`},
    {region:`Americas`, country:`United States`, city:`Austin`, campus:`US194OF01 Austin Southcongress (AL)`, building:`SOUTHCONGRESS`},
    {region:`Americas`, country:`United States`, city:`Nashville`, campus:`US197OF01 Nashville West End Avenue`, building:`NASHVILLE`},
    {region:`Americas`, country:`United States`, city:`Bellevue`, campus:`US205OF01 Bellevue NE 28th Street`, building:`BELLEVUENE28TH`},
    {region:`Americas`, country:`United States`, city:`Boston`, campus:`US208OF01 Boston Twodrydock`, building:`TWODRYDOCK`},
    {region:`Americas`, country:`United States`, city:`Burlington`, campus:`US216OF01 Burlington Woods`, building:`BURLINGTONWOODS`},
    {region:`Americas`, country:`United States`, city:`San Francisco`, campus:`US222OF01 San Francisco Sfmissionrocks`, building:`SFMISSIONROCKS`},
    {region:`Americas`, country:`United States`, city:`San Antonio`, campus:`US226OF01 San Antonio Sanantonio`, building:`SANANTONIO`},
    {region:`APAC`, country:`Vietnam`, city:`Ho Chi Minh, VICT`, campus:`VN001OF01 Ho Chi Minh, Vict Hochiminh`, building:`HOCHIMINH`},
    {region:`Europe`, country:`Germany`, city:`Bad Homburg`, campus:`DE123OF01 Bad Homburg Horexstr`, building:`HOREXSTR`},
    {region:`Other Countries`, country:`Egypt`, city:`Al Qāhirah`, campus:`EG002 CG CFC`, building:`CFC`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`DENALI`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`KANHA`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`PATAGONIA`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`YELLOW STONE`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`SERENGETI`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`KAZIRANGA`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`KAKADU`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`EPIP`, building:`DARTMOOR`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`Building 1`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`Building 2`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`Building 3`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`Building 4`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`EMPLOYEE RELAXATION CENTER`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`BESS`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`CUSTOMER EXPERIENCE CENTER`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`VISITOR'S PLAZA & SECURITY KIOSK`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-1`, building:`UTILITY BLOCK`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-2`, building:`Building 5`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-2`, building:`Building 6`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Phase-2`, building:`UTILITY BLOCK`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`DB 1`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`EMPLOYEE RELAXATION CENTER`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`CAFETERIA`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`TRAINING CENTER`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`EXPERIENCE CENTER`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`CLUB HOUSE`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`VISITOR PLAZA`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`CENTRALISED PLUMBING BLOCK`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 1`, building:`ELECTRICAL SUB STATION`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 2`, building:`TRAINING CENTER 2`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 2`, building:`DB 2`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 2`, building:`PLUMBING BLOCK 2`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Hinjewadi Phase 2`, building:`ELECTRICAL SUB STATION 2`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`UNIT-0`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`UNIT-1`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`UNIT-2`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`UNIT-2A`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`ANNEX`},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`GLC `},
    {region:`APAC`, country:`India`, city:`Pune`, campus:`Talwade`, building:`TOWER-3 `},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`Sipcot`, building:`YUSHAN BUILDING`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`Sipcot`, building:`SUNDARBANS BUILDING`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`Sipcot`, building:`UTILITY BLOCK`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`MIPL`, building:`SOFTWARE DEVELOPMENT BLOCK`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`MIPL`, building:`CUSTOMER CARE BLOCK`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`MIPL`, building:`CAFETERIA BLOCK`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`MIPL`, building:`UTILITY BLOCK`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`Gachibowli`, building:`SDB-1`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`Gachibowli`, building:`SDB-2`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`Gachibowli`, building:`CUSTOMER CARE & RB BLOCK`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`Gachibowli`, building:`CAFETERIA BLOCK`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`Gachibowli`, building:`UTILITY BLOCK`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`Gachibowli`, building:`SDB-3`},
    {region:`APAC`, country:`India`, city:`Noida`, campus:`Noida-SEZ`, building:`TOWER-A`},
    {region:`APAC`, country:`India`, city:`Noida`, campus:`Noida-SEZ`, building:`TOWER-B`},
    {region:`APAC`, country:`India`, city:`Noida`, campus:`Noida-SEZ`, building:`TOWER-C`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`DTP`, building:`DTP B4`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`DTP`, building:`DTP B5`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`DTP`, building:`DTP A5`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`DTP`, building:`DTP A6`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`Ecospace`, building:`5B`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`Ecospace`, building:`6B`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`Global Village`, building:`Global Village`},
    {region:`APAC`, country:`India`, city:`Bangalore`, campus:`Valdel`, building:`Valdel`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`CPCT`, building:`CPCT`},
    {region:`APAC`, country:`India`, city:`Chennai`, campus:`ASV`, building:`ASV chandilya`},
    {region:`APAC`, country:`India`, city:`Trichy`, campus:`VRN`, building:`VRN `},
    {region:`APAC`, country:`India`, city:`Trichy`, campus:`Muthaiya Tower`, building:`Muthaiya Tower`},
    {region:`APAC`, country:`India`, city:`Salem`, campus:`PT Tower`, building:`PT Tower`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`GAR`, building:`Tower-3`},
    {region:`APAC`, country:`India`, city:`Hyderabad`, campus:`GAR`, building:`Tower-4`},
    {region:`APAC`, country:`India`, city:`Coimbatore`, campus:`Infopark`, building:`Hanudevi Infopark`},
    {region:`APAC`, country:`India`, city:`Mumbai`, campus:`Vikroli`, building:`Vikhroli M4`},
    {region:`APAC`, country:`India`, city:`Gurugram`, campus:`Guragon Candor`, building:`Tower-4`},
    {region:`APAC`, country:`India`, city:`Gurugram`, campus:`Guragon Candor`, building:`Tower-5`},
    {region:`APAC`, country:`India`, city:`Gurugram`, campus:`Guragon Candor`, building:`Tower-6`},
    {region:`APAC`, country:`India`, city:`Gandhinagar`, campus:`GandhiNagar`, building:`Gift City`},
    {region:`APAC`, country:`India`, city:`Kolkata`, campus:`Candor`, building:`Candor`},
    {region:`APAC`, country:`India`, city:`Kolkata`, campus:`Candor`, building:`1A Building`},
    {region:`APAC`, country:`India`, city:`Kolkata`, campus:`Candor`, building:`3A Building`},
    {region:`APAC`, country:`India`, city:`Bhubaneshwar`, campus:`Infocity`, building:`Infocity`}
    
]
export default dropdownOptions;